import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const envPath = resolve(repoRoot, '.env');
const outPath = resolve(repoRoot, 'src/environments/environment.ts');

const env = { ...process.env };

if (existsSync(envPath)) {
  const contents = readFileSync(envPath, 'utf8');
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (env[key] === undefined) env[key] = value;
  }
}

const web3formsAccessKey = env.WEB3FORMS_ACCESS_KEY ?? '';

if (!web3formsAccessKey) {
  console.warn(
    '[set-env] WEB3FORMS_ACCESS_KEY is empty — contact forms will not be able to submit.',
  );
}

const fileContents = `// This file is generated by scripts/set-env.mjs. Do not edit by hand.
export const environment = {
  production: ${env.NODE_ENV === 'production'},
  web3formsAccessKey: ${JSON.stringify(web3formsAccessKey)},
} as const;
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, fileContents);
console.log(`[set-env] wrote ${outPath}`);
